default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "FuneralMusic",
      export_method: "app-store"
    )

    upload_to_testflight(
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_id: ENV["APP_STORE_KEY_ID"],
      key_content: ENV["APP_STORE_PRIVATE_KEY"],
      skip_waiting_for_build_processing: true
    )
  end
end
